pipeline {
    agent any
    tools {
        maven 'Maven 3.3'
    }
    stages {
        stage("build") {
            when { changeset "worker/**" }
            steps{
                 echo 'Building worker project'
                 dir ("worker") {
                     sh 'mvn compile'
                 }
            }
        }
        stage("test") {
            when { changeset "worker/**" }
            steps{
                 echo 'Testing worker Project'
                 dir ("worker") {
                     sh 'mvn test'
                 }
            }
        }
        stage("package") {
            when { 
                allOf {
                    changeset "worker/**" ; branch 'master'
                }
            }
            steps{
                 echo 'Packaging Worker project'
                 dir ("worker") {
                     sh 'mvn package'

                 }
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            echo ' I will always say hello'
        }
    }
}
